//! Tor configuration file (`torrc`) generation.

use crate::tor_manager::TorConfig;

pub struct TorrcGenerator;

impl TorrcGenerator {
    /// Generate a complete `torrc` file contents for the given `TorConfig`.
    pub fn generate(config: &TorConfig) -> String {
        let mut lines: Vec<String> = Vec::new();

        lines.push("## torrc generated by HispaShield tor-proxy daemon".to_string());
        lines.push("## DO NOT EDIT MANUALLY — changes will be overwritten".to_string());
        lines.push(String::new());

        // ── Ports ────────────────────────────────────────────────────────────
        lines.push(format!("SocksPort {}", config.socks_port));
        lines.push(format!("ControlPort {}", config.control_port));
        lines.push(format!("DNSPort {}", config.dns_port));
        lines.push(format!(
            "TransPort {} isolateClientAddr isolateSOCKSAuth",
            config.transparent_port
        ));

        // ── Data directory ───────────────────────────────────────────────────
        lines.push(String::new());
        lines.push(format!("DataDirectory {}", config.data_dir));

        // ── Logging ──────────────────────────────────────────────────────────
        lines.push(String::new());
        lines.push(format!(
            "Log notice file {}/tor.log",
            config.data_dir
        ));
        // Also log to stdout so the daemon can watch for "Bootstrapped 100%"
        lines.push("Log notice stdout".to_string());

        // ── DNS / transparent proxy ──────────────────────────────────────────
        lines.push(String::new());
        lines.push("AutomapHostsOnResolve 1".to_string());
        lines.push("AutomapHostsSuffixes .onion,.exit".to_string());
        lines.push("VirtualAddrNetworkIPv4 10.192.0.0/10".to_string());

        // ── Exit node preferences ────────────────────────────────────────────
        lines.push(String::new());
        if !config.exit_nodes.is_empty() {
            let nodes = config.exit_nodes.join(",");
            lines.push(format!("ExitNodes {nodes}"));
            lines.push("StrictNodes 1".to_string());
        }
        if !config.exclude_exit_nodes.is_empty() {
            let excluded = config.exclude_exit_nodes.join(",");
            lines.push(format!("ExcludeExitNodes {excluded}"));
        }

        // ── Security hardening ───────────────────────────────────────────────
        lines.push(String::new());
        lines.push("# Security hardening".to_string());
        lines.push("DisableAllSwap 1".to_string());
        lines.push("HardwareAccel 1".to_string());
        lines.push("SafeSocks 1".to_string());
        lines.push("TestSocks 1".to_string());
        lines.push("WarnUnsafeSocks 1".to_string());
        // Reduce circuit build timeout for mobile
        lines.push("CircuitBuildTimeout 10".to_string());
        lines.push("LearnCircuitBuildTimeout 0".to_string());
        // Isolate streams by destination port (better anonymity)
        lines.push("IsolateDestPort 1".to_string());

        // ── Cookie authentication for the control port ───────────────────────
        lines.push(String::new());
        lines.push("CookieAuthentication 1".to_string());
        lines.push(format!(
            "CookieAuthFile {}/control_auth_cookie",
            config.data_dir
        ));

        lines.push(String::new());
        lines.join("\n")
    }

    /// Write `torrc` to `<data_dir>/torrc`, creating the directory if needed.
    pub fn write(config: &TorConfig) -> anyhow::Result<()> {
        std::fs::create_dir_all(&config.data_dir)?;
        let path = format!("{}/torrc", config.data_dir);
        let content = Self::generate(config);
        std::fs::write(&path, content)?;
        tracing::info!(path, "torrc written");
        Ok(())
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tor_manager::TorConfig;

    fn default_config() -> TorConfig {
        TorConfig {
            socks_port: 9050,
            control_port: 9051,
            dns_port: 5353,
            transparent_port: 9040,
            data_dir: "/data/hispashield/tor".to_string(),
            exit_nodes: vec!["{DE}".to_string(), "{NL}".to_string()],
            exclude_exit_nodes: vec!["{US}".to_string(), "{GB}".to_string()],
            bypass_uids: vec![1000],
        }
    }

    #[test]
    fn contains_socks_port() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("SocksPort 9050"), "Missing SocksPort");
    }

    #[test]
    fn contains_control_port() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("ControlPort 9051"));
    }

    #[test]
    fn contains_dns_port() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("DNSPort 5353"));
    }

    #[test]
    fn contains_trans_port() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("TransPort 9040"));
    }

    #[test]
    fn contains_exit_nodes() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("ExitNodes {DE},{NL}"));
        assert!(torrc.contains("StrictNodes 1"));
    }

    #[test]
    fn contains_exclude_nodes() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("ExcludeExitNodes {US},{GB}"));
    }

    #[test]
    fn contains_automap() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("AutomapHostsOnResolve 1"));
        assert!(torrc.contains("VirtualAddrNetworkIPv4 10.192.0.0/10"));
    }

    #[test]
    fn contains_security_options() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("SafeSocks 1"));
        assert!(torrc.contains("DisableAllSwap 1"));
        assert!(torrc.contains("CookieAuthentication 1"));
    }

    #[test]
    fn no_strict_nodes_without_exit_nodes() {
        let mut cfg = default_config();
        cfg.exit_nodes.clear();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(!torrc.contains("ExitNodes"), "Should not have ExitNodes when list is empty");
        assert!(!torrc.contains("StrictNodes"), "Should not have StrictNodes when no exit nodes");
    }

    #[test]
    fn data_directory_present() {
        let cfg = default_config();
        let torrc = TorrcGenerator::generate(&cfg);
        assert!(torrc.contains("DataDirectory /data/hispashield/tor"));
    }
}
